---
# vars file for check-env
docker_dowload_url: https://download.docker.com/linux/debian/gpg
docker_repo: https://download.docker.com/linux/debian
docker_compose_url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
