---
# tasks file for run-compose-with-ansible
#

    - name: Tear down existing services
      community.docker.docker_compose:
        project_src: docker_compose
        state: absent
    - name: Create and start services
      community.docker.docker_compose:
       project_src: docker_compose
      register: output
    - ansible.builtin.debug:
         var: output
