---
# tasks file for check-env
   
   - name: Check If Docker Is Installed
     command: docker --version
     register: docker_valid
     ignore_errors: yes
   - name: install python
     package:
      name: python3
      state: present
   - name: Install docker and some dependencies
     apt:
      name: python3-pip
      state: present
   - name: Debug Docker Output
     debug:
      var: docker_valid
   - name: install dependencies
     apt:
      name: "{{item}}"
      state: present
      update_cache: yes
     loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
     when: docker_valid.failed
   - name: add GPG key
     apt_key:
      url: "{{ docker_dowload_url }}"
      state: present
     when: docker_valid.failed
   - name: add docker repository
     apt_repository:
      repo: deb "{{ docker_repo }}" bullseye stable
      state: present
     when: docker_valid.failed
   - name: Update packages
     apt:
      update_cache: yes
   - name: install docker
     apt:
      name: "{{item}}"
      state: latest
      update_cache: yes
     loop:
       - docker-ce
       - docker-ce-cli
       - containerd.io
     when: docker_valid.failed
   - name: Install docker python module
     pip:
      name: docker
   - name: make sure docker is active
     service:
      name: docker
      state: started
      enabled: yes
   - name: chmod 666 /var/run/docker.sock
     shell: chmod 666 /var/run/docker.sock
     become: true

   - name: Check If Docker Is Installed
     command: docker-compose --version
     register: docker_compose_valid
     ignore_errors: yes
   
   - name: Debug Docker_compose Output
     debug:
      var: docker_compose_valid

   - name: Install docker-compose from official github repo
     remote_user: ansible_ubuntu_demo
     get_url:
      url : "{{ docker_compose_url }}"
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'
     when: docker_compose_valid.failed
